name: Basic Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Test imports
      run: |
        python -c "import webextract; print('✅ Package imports successfully')"
        python -c "print('✅ Version:', webextract.__version__)"
        python -c "print('✅ Author:', webextract.__author__)"

    - name: Test CLI
      run: |
        python -m webextract.cli version

    - name: Test basic functionality
      run: |
        python -c "
        import webextract
        config = webextract.ConfigBuilder().with_model('test-model').build()
        print('✅ Config builder works')
        print('✅ All basic tests passed!')
        " 